---
title: "Results - Exposure data"
output:
   html_notebook:
    toc: true
    toc_float: true
---


# Results - Descriptive stats for neighborhood exposure

```{r setup, include=FALSE}
# first set up the environment; we need the `tidyverse` and `sf` packages
source("../../code/0-setup/01-setup.R")
library("ggdark")
```

```{r data_input, include=FALSE}
holc_neighborhoods <- 
  st_read("../../data/raw/univ_richmond/mapping_inequality/shapefile/holc_ad_data.shp") %>%
  mutate(city = ifelse(city == "Bronx" | city == "Brooklyn" |  # combines NY boroughs
                         city == "Manhattan" | city == "Staten Island" |
                         city == "Queens", "New York City", city )) %>%
  mutate(city_state = as.factor(paste(city, "-", state))) %>%
  #left_join(holc_cities_year, by = "city_state") %>%
  st_transform(crs_projected) %>%
  st_buffer(dist = 0) %>%  # shortcut to address issue with dataset
  st_transform(crs_nad83) %>%
  mutate(neighborhood = as.factor(neighborho)) %>%
  distinct(neighborhood, .keep_all = TRUE)

holc_buffer_1km_wells_all_preholc <-
  read_csv("../../data/interim/holc_neighborhoods_buffer_1km_wells_all_preholc.csv") %>%
  mutate(neighborhood = as.factor(neighborhood)) %>%
  rename(buffer_1km_wells_preholc_n = buffer_1km_wells_all_n) %>%
  select(-year_appraised)
holc_buffer_1km_wells_all_postholc <-
  read_csv("../../data/interim/holc_neighborhoods_buffer_1km_wells_all_postholc.csv") %>%
  mutate(neighborhood = as.factor(neighborhood)) %>%
  rename(buffer_1km_wells_postholc_n = buffer_1km_wells_all_n) %>%
  select(-year_appraised)

holc_buffer_1km_injection_postholc <-
  read_csv("../../data/interim/holc_neighborhoods_buffer_1km_wells_injection_postholc.csv") %>%
  mutate(neighborhood = as.factor(neighborhood)) %>%
  rename(buffer_1km_injection_postholc_n = buffer_1km_wells_injection_n) %>%
  select(-year_appraised)
```

```{r data_prep, include=FALSE}
holc_exposure <- holc_neighborhoods %>%
  left_join(holc_buffer_1km_wells_all_preholc, by = "neighborhood") %>%
  left_join(holc_buffer_1km_wells_all_postholc, by = "neighborhood") %>%
  left_join(holc_buffer_1km_injection_postholc, by = "neighborhood") %>%
  mutate(buffer_1km_wells_preholc_n  = replace_na(buffer_1km_wells_preholc_n, 0),
         buffer_1km_wells_postholc_n = replace_na(buffer_1km_wells_postholc_n, 0),
         buffer_1km_injection_postholc_n = replace_na(buffer_1km_injection_postholc_n, 0))
```


## Pre-appraisal wells

#### Figure. Pre-appraisal wells

```{r echo=FALSE}
fig <- holc_exposure %>% 
  filter(holc_grade != "E") %>%
  drop_na(holc_grade) %>%
  ggplot() +
  geom_bar(aes(holc_grade, buffer_1km_wells_preholc_n), stat = "identity",
           fill = "#FF7F7F") +
  ylim(0, 10000) +
  labs(x = "HOLC Grade", y = "Pre-appraisal wells (n)") +
  dark_theme_classic()
fig
ggsave("pres_fig_wells_all_preholc.png", plot = fig, 
       height = 5, width = 8, device = "png", path = "../figures/")
```

#### Figure. Pre-appraisal wells by state

```{r echo=FALSE}
fig <- holc_exposure %>% 
  filter(state %in% c("CA", "MO", "OH", "OK", "PA", "WV")) %>%
  filter(holc_grade != "E") %>%
  drop_na(holc_grade) %>%
  ggplot() +
  geom_bar(aes(holc_grade, buffer_1km_wells_preholc_n), stat = "identity",
           fill = "#FF7F7F") +
  ylim(0, 4500) +
  labs(x = "HOLC Grade", y = "Pre-appraisal wells (n)") +
  facet_wrap(. ~ state) +
  dark_theme_classic()
ggsave("pres_fig_wells_all_preholc_states.png", plot = fig, 
       height = 5, width = 8, device = "png", path = "../figures/")
```


## Post-appraisal wells

#### Figure. Post-appraisal wells

```{r echo=FALSE}
fig <- holc_exposure %>% 
  filter(holc_grade != "E") %>%
  drop_na(holc_grade) %>%
  ggplot() +
  geom_bar(aes(holc_grade, buffer_1km_wells_postholc_n), stat = "identity",
           fill = "lightblue") +
  ylim(0, 10000) +
  labs(x = "HOLC Grade", y = "Post-appraisal wells (n)") +
  dark_theme_classic()
ggsave("pres_fig_wells_all_postholc.png", plot = fig, 
       height = 5, width = 8, device = "png", path = "../figures/")
```

#### Figure. Post-appraisal wells by state

```{r echo=FALSE}
fig <- holc_exposure %>% 
  filter(state %in% c("CA", "MO", "OH", "OK", "PA", "WV")) %>%
  filter(holc_grade != "E") %>%
  drop_na(holc_grade) %>%
  ggplot() +
  geom_bar(aes(holc_grade, buffer_1km_wells_postholc_n), stat = "identity",
           fill = "lightblue") +
  ylim(0, 4500) +
  labs(x = "HOLC Grade", y = "Post-appraisal wells (n)") +
  facet_wrap(. ~ state) +
  dark_theme_classic()
ggsave("pres_fig_wells_all_postholc_states.png", plot = fig, 
       height = 5, width = 8, device = "png", path = "../figures/")
```


## Injection wells


#### Figure. Post-appraisal wells

```{r echo=FALSE}
fig <- holc_exposure %>% 
  filter(holc_grade != "E") %>%
  drop_na(holc_grade) %>%
  ggplot() +
  geom_bar(aes(holc_grade, buffer_1km_injection_postholc_n), stat = "identity",
           fill = "blue") +
  ylim(0, 600) +
  labs(x = "HOLC Grade", y = "Post-appraisal injection wells (n)") +
  dark_theme_classic()
ggsave("pres_fig_wells_injection_postholc.png", plot = fig, 
       height = 5, width = 8, device = "png", path = "../figures/")
```

